-- MySQL Script generated by MySQL Workbench
-- 05/15/17 08:14:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema s1db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema s1db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `s1db` DEFAULT CHARACTER SET utf8 ;
USE `s1db` ;

-- -----------------------------------------------------
-- Table `s1db`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s1db`.`Category` ;

CREATE TABLE IF NOT EXISTS `s1db`.`Category` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s1db`.`Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s1db`.`Store` ;

CREATE TABLE IF NOT EXISTS `s1db`.`Store` (
  `store_id` INT NOT NULL AUTO_INCREMENT,
  `store_name` VARCHAR(250) NOT NULL,
  `store_address` VARCHAR(255) NOT NULL,
  `store_email` VARCHAR(250) NOT NULL,
  `store_phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`store_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s1db`.`Category_In_Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s1db`.`Category_In_Store` ;

CREATE TABLE IF NOT EXISTS `s1db`.`Category_In_Store` (
  `cat_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`cat_id`, `store_id`),
  INDEX `fk_Category_has_Store_Store1_idx` (`store_id` ASC),
  INDEX `fk_Category_has_Store_Category_idx` (`cat_id` ASC),
  CONSTRAINT `fk_Category_has_Store_Category`
    FOREIGN KEY (`cat_id`)
    REFERENCES `s1db`.`Category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Category_has_Store_Store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `s1db`.`Store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s1db`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s1db`.`Brand` ;

CREATE TABLE IF NOT EXISTS `s1db`.`Brand` (
  `brand_id` INT NOT NULL,
  `brand_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s1db`.`Store_In_Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s1db`.`Store_In_Brand` ;

CREATE TABLE IF NOT EXISTS `s1db`.`Store_In_Brand` (
  `strore_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`strore_id`, `brand_id`),
  INDEX `fk_Store_has_Brand_Brand1_idx` (`brand_id` ASC),
  INDEX `fk_Store_has_Brand_Store1_idx` (`strore_id` ASC),
  CONSTRAINT `fk_Store_has_Brand_Store1`
    FOREIGN KEY (`strore_id`)
    REFERENCES `s1db`.`Store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Store_has_Brand_Brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `s1db`.`Brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s1db`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s1db`.`User` ;

CREATE TABLE IF NOT EXISTS `s1db`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(50) NOT NULL,
  `user_password` VARCHAR(50) NOT NULL,
  `user_location` VARCHAR(50) NULL,
  `user_recent_search` VARCHAR(50) NULL,
  `user_favorite` VARCHAR(50) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s1db`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s1db`.`Comment` ;

CREATE TABLE IF NOT EXISTS `s1db`.`Comment` (
  `store_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_comment` VARCHAR(512) NULL,
  PRIMARY KEY (`store_id`, `user_id`),
  INDEX `fk_Store_has_User_User1_idx` (`user_id` ASC),
  INDEX `fk_Store_has_User_Store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_Store_has_User_Store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `s1db`.`Store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Store_has_User_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `s1db`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s1db`.`Mall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s1db`.`Mall` ;

CREATE TABLE IF NOT EXISTS `s1db`.`Mall` (
  `mall_id` INT NOT NULL AUTO_INCREMENT,
  `mall_name` VARCHAR(50) NOT NULL,
  `mall_location` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`mall_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s1db`.`Mall_has_Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s1db`.`Mall_has_Store` ;

CREATE TABLE IF NOT EXISTS `s1db`.`Mall_has_Store` (
  `mall_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`mall_id`, `store_id`),
  INDEX `fk_Mall_has_Store_Store1_idx` (`store_id` ASC),
  INDEX `fk_Mall_has_Store_Mall1_idx` (`mall_id` ASC),
  CONSTRAINT `fk_Mall_has_Store_Mall1`
    FOREIGN KEY (`mall_id`)
    REFERENCES `s1db`.`Mall` (`mall_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mall_has_Store_Store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `s1db`.`Store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
